meta_product_name: "Find the right coach"
meta_title: "Find the right trainer - Find a personal coach to meet your needs"
meta_description: ""
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
