meta_product_name: "Find the right trainer"
meta_title: "Find the right trainer - Find a personal trainer to meet your needs"
meta_description: "find a personal trainer to fit your needs,and gain new skills have a professional trainer help you"
meta_image: "girls.jpeg"                       # should exist in `app/assets/images/`

