test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

  local:
    service: Disk
    root: <%= Rails.root.join("storage") %>

  amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :AKIAIWZLHIXSO5QZWTYA) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :_5I/NU0jzZJG+fvCwgnNWh2yd4qLyhjCrtoiqrWaz) %>
  region: eu
  bucket: [ffyourptrainer]

















# amazon:
#      service: S3
#      access_key_id: <%= ENV['BUCKETEER_AWS_AKIAIWZLHIXSO5QZWTYA'] %>
#      secret_access_key: <%= ENV['BUCKETEER_AWS_5I/NU0jzZJG+fvCwgnNWh2yd4qLyhjCrtoiqrWaz'] %>
#      region: <%= ENV['BUCKETEER_AWS_global'] %>
#      bucket: <%= ENV['BUCKETEER_ffyourptrainer'] %>















 # google:
 #      service: GCS
 #      credentials: <%= Rails.root.join("path/to/keyfile.json") %>
 #      project: "My project"
 #      bucket: "erez"
